name: Data Preprocessing Pipeline

on:
  push:
    branches:
      - main

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
    # Check out repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.7'

    # Install Depedensi
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn joblib seaborn matplotlib

    # Jalankan Script Otomatisasi
    - name: Run Preprocessing Script
      run: python preprocessing/automate_RatuayuNurfajar.py

    # Upload Hasil Dataset
    - name: Upload Processed Dataset
      uses: actions/upload-artifact@v4
      with:
        name: processed-dataset
        path: preprocessing/student_performance_preprocessing/
        retention-days: 1